line_sensor_node:
  ros__parameters:
    base_frame: base_link
    apply_tare: true
    publish_rate: 30.0
    max_range: 4.0
    thresh_cliff_mm: 10.0
    thresh_obstacle_mm: 10.0
    publish_raw_scans: true
    scan_range_min: 0.05
    scan_range_max: 4.0
    robot_client_ip: "127.0.0.1"
